PAGE = {
    'lang': 'es', 'en': 'pregnancy-back-pelvic-pain',
    'reviewed': '2026-10-01',   # draft until a Spanish speaker reviews it
    'title': "Dolor de espalda y pelvis en el embarazo, Bakersfield | ARI PT",
    'description': "¿Dolor de espalda, cadera o pelvis en el embarazo? Terapia física prenatal suave e individual para mujeres en Bakersfield, CA. Sin referencia médica.",
    'crumb': "Dolor de espalda y pelvis en el embarazo",
    'eyebrow': "Salud de la mujer",
    'h1': "Dolor de espalda y pelvis durante el embarazo en",
    'lead': "El dolor en la parte de atrás de la pelvis, en el hueso púbico o en la parte baja de la espalda es muy común en el embarazo. Que sea común no significa que tenga que aguantarlo. La terapia física suave puede ayudar.",
    'answer': "<strong>Sí, la terapia física puede ayudar con el dolor de espalda y de pelvis durante el embarazo.</strong> El dolor en la parte baja de la espalda y en la cintura pélvica afecta a muchas mujeres embarazadas, y el ejercicio y la terapia física son formas seguras y recomendadas de aliviar el dolor y mantenerse activa. En ARI Physical Therapy en Bakersfield, la atención prenatal es individual con un fisioterapeuta con licencia en un cuarto privado, y coordinamos con su ginecólogo u obstetra cuando es necesario.",
    'signs': [
        "Dolor en la parte baja de la espalda, o en la parte de atrás de la pelvis, cerca de los hoyuelos",
        "Dolor en la parte de adelante de la pelvis o en el hueso púbico",
        "Dolor al voltearse en la cama, al pararse en una pierna o al vestirse",
        "Dolor al subir escaleras o al subir y bajar del carro",
        "Dolor que se extiende a la nalga o baja por la parte de atrás del muslo",
        "Pérdidas de orina al toser, estornudar o reír",
    ],
    'why': [
        ("Por qué sucede",
         "<p>A medida que su bebé crece, cambian su postura y su centro de gravedad, y las hormonas ayudan a que las articulaciones y los ligamentos de la pelvis se aflojen para prepararse para el parto. Los músculos de la espalda, las caderas, el vientre y el piso pélvico tienen que trabajar más y de otra manera. El <strong>dolor de la cintura pélvica</strong>, que se siente en la parte de atrás de la pelvis o en el hueso púbico, es especialmente común y a menudo empeora al caminar, al subir escaleras y al pararse en una pierna.</p>"),
        ("Cómo ayuda la terapia física",
         "<p>El tratamiento es suave y se adapta a cada etapa del embarazo. Puede incluir ejercicios que dan soporte a la pelvis y la espalda, tratamiento manual, formas más fáciles de moverse, dormir y levantarse de la cama, y consejos sobre una faja de soporte si le puede ayudar. También podemos trabajar el piso pélvico, para ayudar con las pérdidas de orina y para prepararse para el parto y la recuperación después. Para después de que nazca su bebé, vea nuestra página de <a href=\"postpartum-therapy.html\">terapia posparto (en inglés)</a>.</p>"),
    ],
    'steps': [
        ("Una evaluación individual", "Su primera visita dura de 45 a 60 minutos, en un cuarto privado. Le preguntamos sobre su embarazo y su dolor, revisamos cómo se mueve y le explicamos lo que encontramos. No se hace nada sin su consentimiento."),
        ("Tratamiento suave", "Ejercicios para dar soporte a la pelvis, la espalda y las caderas, tratamiento manual, posiciones para dormir y para las tareas diarias, y atención del piso pélvico si la necesita, todo ajustado a medida que avanza su embarazo."),
        ("Un plan hasta el parto y después", "Un programa en casa que cambia en cada trimestre, consejos para mantenerse activa de forma segura y un plan para su recuperación después de que nazca su bebé."),
    ],
    'red_flags_intro': "Llame a su ginecólogo u obstetra, o busque atención de emergencia, si tiene:",
    'red_flags': [
        "Sangrado vaginal o salida de líquido",
        "Endurecimiento o cólicos regulares en el vientre, o dolor de espalda que va y viene como en olas, antes de las 37 semanas",
        "Un dolor de cabeza fuerte, cambios en la vista o hinchazón repentina de la cara o las manos",
        "Dolor, hinchazón o calor en una pantorrilla, o dolor en el pecho o falta de aire",
        "Fiebre, o dolor o ardor al orinar",
        "Adormecimiento en la ingle o problemas nuevos para controlar la vejiga o los intestinos",
    ],
    'faq_title': "Preguntas frecuentes sobre el dolor de espalda y pelvis en el embarazo",
    'faqs': [
        ("¿Es segura la terapia física durante el embarazo?", "Sí. La terapia física durante el embarazo es suave y se adapta a cuántas semanas de embarazo tiene. Evitamos posiciones y tratamientos que no son apropiados en el embarazo, y coordinamos con su ginecólogo u obstetra cuando es necesario."),
        ("¿Se me quitará el dolor después del parto?", "Para muchas mujeres, el dolor de espalda y pelvis del embarazo mejora en las semanas después del parto, pero para algunas continúa. Tratarlo durante el embarazo puede hacerla sentir más cómoda ahora, y podemos seguir ayudándole después de que nazca su bebé."),
        ("¿Se hace terapia del piso pélvico durante el embarazo?", "Puede hacerse. La atención del piso pélvico durante el embarazo puede ayudar con las pérdidas de orina y la sensación de pesadez, y ayudarle a aprender a relajar y coordinar el piso pélvico para el parto. Primero le explicamos todo, y usted decide con qué se siente cómoda."),
        ("¿Debo usar una faja de soporte para el embarazo?", "Una faja de soporte ayuda a algunas mujeres con dolor de la cintura pélvica, sobre todo al caminar y al estar de pie. Su fisioterapeuta le puede decir si es probable que le ayude y cómo usarla."),
    ],
    'side': "La atención prenatal en ARI es individual con un fisioterapeuta con licencia, en un cuarto privado.",
    'related': [
        ("Pérdidas de orina", "perdidas-de-orina-incontinencia.html"),
        ("Ciática y dolor de espalda", "ciatica-dolor-de-espalda.html"),
        ("Terapia del piso pélvico para mujeres (en inglés)", "pelvic-floor-therapy.html"),
        ("Terapia posparto (en inglés)", "postpartum-therapy.html"),
    ],
    'condition': "Dolor lumbar y de la cintura pélvica relacionado con el embarazo",
    'alt_names': ["Dolor de la cintura pélvica", "Dolor de espalda en el embarazo", "Dolor de pelvis en el embarazo", "Disfunción de la sínfisis del pubis", "Dolor sacroilíaco en el embarazo", "Dolor de espalda prenatal"],
    'therapy': "Terapia física prenatal: ejercicio, terapia manual, atención del piso pélvico y orientación sobre el movimiento",
}
