PAGE = {
    'reviewed': '2026-09-30',   # clinically reviewed by Deepa
    'title': 'Pregnancy Back & Pelvic Pain PT in Bakersfield | ARI PT',
    'description': 'Back, hip or pelvic pain during pregnancy? Gentle, one-on-one prenatal physical therapy for women in Bakersfield, CA. No referral needed.',
    'crumb': 'Pregnancy Back &amp; Pelvic Pain',
    'eyebrow': 'Women&rsquo;s Health',
    'h1': 'Back and Pelvic Pain During Pregnancy in',
    'lead': 'Pain at the back of your pelvis, in the pubic bone or low back is very common in pregnancy. Common doesn\'t mean you just have to put up with it. Gentle physical therapy can help.',
    'answer': '<strong>Yes, physical therapy can help back and pelvic pain during pregnancy.</strong> Low back and pelvic girdle pain affect many pregnant women, and exercise and physical therapy are safe, recommended ways to ease pain and stay active. At ARI Physical Therapy in Bakersfield, prenatal care is one-on-one with a licensed physical therapist in a private room, and we coordinate with your OB when needed.',
    'signs': [
        'Pain in the low back, or at the back of the pelvis near the dimples',
        'Pain at the front of the pelvis or pubic bone',
        'Pain turning over in bed, standing on one leg or getting dressed',
        'Pain climbing stairs or getting in and out of the car',
        'Pain that spreads into the buttock or down the back of the thigh',
        'Leaking urine when you cough, sneeze or laugh',
    ],
    'why': [
        ('Why it happens',
         '<p>As your baby grows, your posture and center of gravity change, and hormones help the pelvic joints and ligaments loosen to prepare for birth. The muscles of the back, hips, belly and pelvic floor have to work harder and differently. <strong>Pelvic girdle pain</strong>, felt at the back of the pelvis or at the pubic bone, is especially common and often gets worse with walking, stairs and standing on one leg.</p>'),
        ('How physical therapy helps',
         '<p>Treatment is gentle and adjusted to each stage of pregnancy. It can include exercises that support the pelvis and back, hands-on care, easier ways to move, sleep and get out of bed, and advice on a support belt if it would help. We can also work on the pelvic floor, to help with leaking and to prepare for birth and recovery afterward. After your baby arrives, see <a href="postpartum-therapy.html">postpartum therapy</a>.</p>'),
    ],
    'steps': [
        ('A one-on-one evaluation', 'Your first visit takes about 45 to 60 minutes, in a private room. We ask about your pregnancy and your pain, check how you move, and explain what we find. Nothing is done without your consent.'),
        ('Gentle treatment', 'Exercises to support the pelvis, back and hips, hands-on care, positions for sleep and daily tasks, and pelvic floor care if you need it, all adjusted as your pregnancy progresses.'),
        ('A plan through birth and after', 'A home program that changes with each trimester, tips for staying active safely, and a plan for recovery after your baby arrives.'),
    ],
    'red_flags_intro': 'Call your OB, or get emergency care, if you have:',
    'red_flags': [
        'Vaginal bleeding or leaking fluid',
        'Regular tightening or cramping in your belly, or back pain that comes and goes in waves before 37 weeks',
        'A severe headache, vision changes or sudden swelling of the face or hands',
        'Pain, swelling or warmth in one calf, or chest pain or shortness of breath',
        'Fever, or pain or burning when you urinate',
        'Numbness in the groin or new trouble controlling your bladder or bowels',
    ],
    'faq_title': 'Pregnancy back and pelvic pain FAQs',
    'faqs': [
        ('Is physical therapy safe during pregnancy?', 'Yes. Physical therapy during pregnancy is gentle and adjusted to how far along you are. We avoid positions and treatments that aren\'t appropriate in pregnancy, and we coordinate with your OB when needed.'),
        ('Will the pain go away after I give birth?', 'For many women, pregnancy back and pelvic pain improves in the weeks after birth, but for some it lingers. Treating it during pregnancy can make you more comfortable now, and we can keep helping after your baby arrives.'),
        ('Does pelvic floor therapy happen during pregnancy?', 'It can. Pelvic floor care during pregnancy can help with leaking and heaviness, and help you learn to relax and coordinate the pelvic floor for birth. We explain everything first, and you decide what you\'re comfortable with.'),
        ('Should I wear a pregnancy support belt?', 'A support belt helps some women with pelvic girdle pain, especially for walking and standing. Your therapist can tell you whether one is likely to help you and how to wear it.'),
    ],
    'side': 'Prenatal care at ARI is one-on-one with a licensed physical therapist, in a private room.',
    'related': [('Pelvic Floor Therapy for Women', 'pelvic-floor-therapy.html'), ('Postpartum Therapy', 'postpartum-therapy.html'), ('Bladder Leaks', 'bladder-leaks-incontinence.html'), ('Diastasis Recti', 'diastasis-recti.html')],
    # checklist phrases on service pages that link here once this page is live (release.py)
    'links_from': [('services.html', 'Prenatal back and pelvic pain', 'Prenatal back and pelvic pain'), ('postpartum-therapy.html', 'Prenatal back &amp; pelvic pain', 'Prenatal back &amp; pelvic pain')],
    'condition': 'Pregnancy-related low back and pelvic girdle pain',
    'alt_names': ['Pelvic girdle pain', 'Pregnancy back pain', 'Symphysis pubis dysfunction', 'SI joint pain in pregnancy', 'Prenatal back pain'],
    'therapy': 'Prenatal physical therapy: exercise, manual therapy, pelvic floor care and movement guidance',
}
