PAGE = {
    'lang': 'es', 'en': 'post-surgery-rehab',
    'reviewed': None,   # draft until a Spanish speaker reviews it
    'title': "Rehabilitación después de cirugía en Bakersfield | ARI PT",
    'description': "Terapia física individual después de cirugía en Bakersfield, CA, coordinada con su cirujano: reemplazo de articulación, columna, LCA y manguito rotador.",
    'crumb': "Después de una cirugía",
    'eyebrow': "Después de una cirugía",
    'h1': "Terapia física después de una cirugía en",
    'lead': "Rehabilitación individual y organizada, coordinada con su cirujano, para recuperar la movilidad, reconstruir la fuerza y proteger sus resultados.",
    'answer': "<strong>La cirugía es solo el primer paso: lo que pasa durante la recuperación determina su resultado.</strong> En ARI Physical Therapy, la rehabilitación después de la cirugía es individual y está coordinada de cerca con el protocolo de su cirujano. Así reducimos al mínimo el tejido cicatricial, recuperamos la movilidad y reconstruimos la fuerza con un avance seguro y organizado.",
    'signs_h': "Cirugías después de las cuales le ayudamos",
    'signs': [
        "Reemplazo total de articulación (rodilla, cadera, hombro)",
        "Rehabilitación después de una cirugía de columna",
        "Recuperación después de una reconstrucción del LCA y de otros ligamentos",
        "Rehabilitación después de una cirugía del manguito rotador o del hombro",
        "Manejo de cicatrices y heridas quirúrgicas",
        "Atención coordinada con su equipo quirúrgico",
    ],
    'why': [],
    'steps': [
        ("Una evaluación alineada con su cirujano", "Su primera visita (de 45 a 60 minutos aproximadamente) revisa su procedimiento y el protocolo de su cirujano, y evalúa su movilidad, su fuerza y las precauciones que debe seguir ahora."),
        ("Un plan de rehabilitación por fases", "Atención manual y ejercicio progresivo que respetan sus tiempos de sanación. Su plan avanza de forma segura, desde proteger la reparación hasta recuperar toda su fuerza."),
        ("Un regreso a sus actividades con confianza", "Reconstruimos su fuerza y su función, y le guiamos de vuelta a los movimientos y actividades que le importan, mientras reducimos el riesgo de contratiempos."),
    ],
    'callout': False,
    'callout_html': "<div class=\"callout\"><strong>No necesita una referencia aparte para empezar.</strong> En California puede ver a un fisioterapeuta directamente hasta por 12 visitas o 45 días. La mayoría de los pacientes llegan después de la cirugía con un protocolo de su cirujano, y de cualquier forma coordinamos con su equipo quirúrgico. Algunos seguros todavía piden una referencia para cubrir el tratamiento; llámenos al <a href=\"tel:6612828584\">(661) 282-8584</a> y le ayudamos a verificarlo.</div>",
    'red_flags': [],
    'faq_title': "Preguntas frecuentes sobre la rehabilitación después de una cirugía",
    'faqs': [
        ("¿Cuándo debo empezar la rehabilitación después de la cirugía?", "Depende de su procedimiento y del protocolo de su cirujano. Muchos pacientes empiezan entre unos días y unas semanas después de la cirugía. Coordinamos directamente con su equipo quirúrgico para que su rehabilitación empiece en el momento adecuado y siga las precauciones correctas."),
        ("¿Trabajan con mi cirujano?", "Sí. Diseñamos su programa según el protocolo postoperatorio de su cirujano y coordinamos la atención para que todos estén de acuerdo sobre sus tiempos de recuperación y sus precauciones."),
        ("¿Qué pasa en la primera visita?", "Su evaluación inicial dura de 45 a 60 minutos aproximadamente. Revisamos su procedimiento y el protocolo de su cirujano, evaluamos su movilidad y su fuerza actuales, y empezamos su plan de recuperación personalizado."),
    ],
    'side': "La rehabilitación después de una cirugía en ARI es individual con un fisioterapeuta con licencia.",
    'related': [
        ("Lesiones deportivas", "lesiones-deportivas.html"),
        ("Hombro congelado y manguito rotador", "hombro-congelado-manguito-rotador.html"),
        ("Rehabilitación de reemplazo de rodilla y cadera (en inglés)", "knee-hip-replacement-rehab.html"),
        ("Rehabilitación después de cirugía de columna (en inglés)", "spine-surgery-rehab.html"),
    ],
    'condition': "Recuperación después de una cirugía ortopédica",
    'alt_names': ["Rehabilitación postoperatoria", "Terapia física postoperatoria", "Fisioterapia después de una cirugía", "Terapia física después de una operación", "Rehabilitación después de un reemplazo de rodilla", "Rehabilitación después de un reemplazo de cadera", "Rehabilitación después de una cirugía de columna", "Rehabilitación después de una reconstrucción del LCA", "Rehabilitación después de una cirugía del manguito rotador"],
    'therapy': "Terapia física postoperatoria: rehabilitación por fases coordinada con el protocolo del cirujano",
}
