PAGE = {
    'lang': 'es', 'en': 'vertigo-dizziness-bppv',
    'reviewed': '2026-10-01',   # borrador hasta que lo revise una persona hispanohablante
    'title': "Terapia para vértigo y mareo (VPPB) en Bakersfield | ARI PT",
    'description': "¿El cuarto le da vueltas al voltearse en la cama o mirar hacia arriba? Terapia física para el vértigo y el VPPB en Bakersfield, CA. Sin referencia médica.",
    'crumb': "Vértigo y mareo",
    'eyebrow': "Mareo y equilibrio",
    'h1': "Tratamiento de vértigo y mareo (VPPB) en",
    'lead': "Si el cuarto le da vueltas por unos segundos cuando se voltea en la cama, se acuesta o mira hacia arriba, puede tener VPPB (BPPV en inglés), la causa más común del vértigo. Por lo general se trata muy bien con terapia física, a menudo en solo unas pocas visitas.",
    'answer': "<strong>Sí, la terapia física puede tratar el vértigo causado por el VPPB.</strong> El VPPB (vértigo posicional paroxístico benigno) ocurre cuando unos pequeños cristales de calcio del oído interno se mueven al lugar equivocado, y entonces ciertos movimientos de la cabeza provocan una sensación breve e intensa de que todo da vueltas. La guía de práctica clínica de la American Academy of Otolaryngology&ndash;Head and Neck Surgery recomienda maniobras de reposicionamiento, como la maniobra de Epley, para regresar los cristales a su lugar. Un fisioterapeuta capacitado puede identificar qué oído y qué conducto están afectados y tratarlo, y muchas personas se sienten mucho mejor en una a tres sesiones.",
    'signs': [
        "El cuarto le da vueltas cuando se voltea en la cama o se acuesta",
        "Mirar hacia una repisa alta o echar la cabeza hacia atrás lo provoca",
        "Agacharse o levantarse de la cama le marea",
        "Las vueltas duran segundos, por lo general menos de un minuto",
        "Siente náuseas o se siente inestable por un rato después",
        "Ha empezado a dormir semisentado o a evitar ciertas posiciones",
    ],
    'why': [
        ("No todo mareo es VPPB",
         "<p>&ldquo;Mareo&rdquo; puede significar que todo da vueltas, sentirse aturdido, sentir que se va a desmayar o sentirse inestable al estar de pie, y cada uno tiene causas diferentes. El VPPB es el clásico mareo breve, con vueltas, que aparece con un cambio en la posición de la cabeza. Otros problemas del oído interno, como la neuritis vestibular, pueden dejarle con un mareo que no se quita y mal equilibrio, y estos a menudo mejoran con <strong>rehabilitación vestibular</strong>: ejercicios específicos que ayudan a su cerebro y a su sistema del equilibrio a adaptarse. Su evaluación aclara qué tipo tiene, y si parece que se trata de otra cosa, se lo diremos y le indicaremos el médico adecuado.</p>"),
    ],
    'steps': [
        ("Una evaluación individual", "Su primera visita dura de 45 a 60 minutos. Le preguntamos exactamente cuándo le da el mareo, y luego hacemos pruebas de posición mientras observamos el movimiento de sus ojos, lo que muestra si la causa es el VPPB y qué oído está afectado. Las pruebas pueden provocar las vueltas por un momento; su fisioterapeuta se queda a su lado."),
        ("Tratamiento de reposicionamiento", "Si es VPPB, su fisioterapeuta guía su cabeza y su cuerpo por una serie de posiciones para regresar los cristales a donde deben estar. La maniobra depende de qué conducto está afectado, y por eso las pruebas son importantes."),
        ("Equilibrio y seguimiento", "Volvemos a revisar en la siguiente visita y repetimos la maniobra si es necesario. Si todavía se siente inestable, agregamos ejercicios de equilibrio y vestibulares, además de un programa sencillo en casa."),
    ],
    'red_flags_intro': "Vea a un médico pronto si el mareo viene con desmayos, dolor de pecho o latidos acelerados, pérdida repentina de la audición, o si es constante en lugar de aparecer con el movimiento.</p><p><strong>Llame al 911</strong> si el mareo aparece de repente junto con cualquiera de estos síntomas, porque pueden ser señales de un derrame cerebral:",
    'red_flags': [
        "Un dolor de cabeza repentino y fuerte, diferente a sus dolores de cabeza normales",
        "Visión doble o pérdida de la vista",
        "Dificultad para hablar (habla arrastrada) o para entender lo que le dicen",
        "Un lado de la cara caído",
        "Debilidad o adormecimiento en un brazo o una pierna, sobre todo de un solo lado",
        "Dificultad para caminar o pérdida repentina de la coordinación",
    ],
    'faq_title': "Preguntas frecuentes sobre el vértigo",
    'faqs': [
        ("¿De verdad un fisioterapeuta puede quitar el vértigo?", "Para el VPPB, a menudo sí. El VPPB se debe a cristales del oído interno fuera de lugar, y las maniobras de reposicionamiento que hace un fisioterapeuta capacitado los regresan a su lugar. Muchas personas se sienten mucho mejor en una a tres sesiones."),
        ("¿Es lo mismo que la maniobra de Epley que vi en internet?", "La maniobra de Epley es uno de los tratamientos de reposicionamiento. Solo funciona para el VPPB en un conducto en particular, del lado correcto. Una evaluación identifica qué oído y qué conducto están afectados, para usar la maniobra correcta."),
        ("¿El tratamiento me va a marear?", "Puede ser, por un momento. Las pruebas y la maniobra pueden provocar las vueltas por unos segundos, y eso es de esperarse. Su fisioterapeuta se queda con usted y va a su ritmo."),
        ("¿El vértigo puede regresar?", "El VPPB puede regresar, a veces meses o años después. La buena noticia es que por lo general responde de nuevo al mismo tratamiento, y su fisioterapeuta puede enseñarle qué señales vigilar."),
    ],
    'side': "La atención para el vértigo en ARI es individual con un fisioterapeuta con licencia.",
    'related': [("Equilibrio y prevención de caídas", "equilibrio-y-prevencion-de-caidas.html"), ("Dolor de cuello y dolores de cabeza", "dolor-de-cuello-y-dolores-de-cabeza.html"), ("Programas de bienestar (en inglés)", "wellness-programs.html")],
    'condition': "Vértigo posicional paroxístico benigno (VPPB)",
    'alt_names': ["Vértigo", "Vértigo posicional", "Mareo", "Mareos al acostarse", "Cristales del oído interno", "BPPV"],
    'therapy': "Maniobras de reposicionamiento canalicular (por ejemplo, la maniobra de Epley) y rehabilitación vestibular",
}
